### PR TITLE
Update action.yml to handle the Hedera version

### PR DESCRIPTION
**Pull request by Atharva1723**
Fixes issue #4
**Added Optional Input Parameter:**

1. Introduced hederaVersion as an optional input parameter in the action's metadata.
2. The default value for this parameter is set to the current Mainnet version (v0.52.2), ensuring compatibility with the latest release.

### CODE REVIEW

**Comment by hendrikebbers** [comment]
issue for the PR https://github.com/OpenElements/hedera-solo-action/issues/4

**Comment by hendrikebbers** [comment]
@Atharva1723 the definition of the param looks good. But it need to be used in the script. Otherwise it has no effect.

**Comment by hendrikebbers** [comment]
this line need to be refactored:
`        solo init -i node0 -t v0.51.5 -n solo-test --key-format pem --profile local
`

**Comment by Atharva1723** [comment]
> this line need to be refactored: ` solo init -i node0 -t v0.51.5 -n solo-test --key-format pem --profile local`

ok

**Comment by Atharva1723** [comment]
Added please check

**Pull request merged**
