### PR TITLE
2 add json rpc relay

### LINKED ISSUE #2: Deploy (optional) JSON-RPC-Relay
## 🆕🐥 First Timers Only

This issue is reserved for people who have never contributed to hedera-enterprise or any open source project in general.
We know that creating a pull request (PR) is a major barrier for new contributors.
The goal of this issue and all other issues labeled by [**'good first issue'**](https://github.com/OpenElements/hedera-enterprise/labels/good%20first%20issue) is to help you make your first contribution to Hedera.

## 👾 Description of the issue

Today, we support the (optional) `installMirrorNode` input parameter to start a Mirror Node instance as part of the setup. Next to a Mirror Node we can add a JSON-RPC-Relay to the installation. The relay can be installed by the `solo relay deploy` command. General information about the JSON-RPC-Relay can be found [here](https://www.hashgraph.com/hashio/).

### Suggested solution

Provide an additional (optional) input parameter `installRelay` that is `false` by default. If the parameter is set to `true` the JSON-RPC-Relay will be added by the GitHub Action.

## 📋 Step by step guide to do a contribution

If you have never contributed to an open source project at GitHub, the following step-by-step guide will introduce you to the workflow. 
A more detailed general documentation of the GitHub PR workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] **Claim this issue:** Comment below that you are interested in working on the issue
- [ ] **Wait for assignment:** A community member with the given rights will add you as an assignee of the issue
- [ ] **Fork the repository:** You can do that in GitHub (by simply clicking the 'fork' button).
- [ ] **Check out the forked repository**
- [ ] **Create a feature branch** for the issue. We do not have a hard naming definition for branches but it is best practice to prefix the branch name with the issue id.
- [ ] **Solve the issue** in your branch.
- [ ] **Commit your changes:** to your branch
- [ ] **Start a Pull Request (PR)**: in the hedera-enterprise repository
- [ ] **Check GitHub Actions:** Several GitHub Actions will be triggered automatically for each PR. If a GitHub Action fails and you do not understand the cause of that error do not hesitate to add a comment to the PR and ask the community for support.
- [ ] **Wait for reviews:** Members of the community will review your PR. If a reviewer finds any missing pieces or a problem, he or she will start a discussion with you and describe the next steps for solving the problem.
- [ ] **You did it 🎉:** We will merge the fix in the develop branch. Thanks for being part of our community as an open-source contributor ❤️

## 🎉 Contribute to Hacktoberfest

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a chance to receive cool goodies like a T-Shirt. 🎽

## 🤔 Additional informantion

If you have any questions, just ask us directly in this issue by adding a comment. You can join the Hedera community chat at [Discord](https://hedera.com/discord). A general manual about open-source contributions can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

### PR DESCRIPTION
**Pull request by Firdous2307**
## Description
This PR adds the ability to install a JSON-RPC-Relay as part of the Hedera network setup process.

## Changes
- Added a new `installRelay` input parameter to `action.yml`
- Implemented relay installation logic in `setup.sh`
- Updated README.md with information about the new parameter
- Updated `setup.sh` to handle the new parameter
- Update conditional logic for both `installMirrorNode` and `installRelay` to use the `if` statement directly in the GitHub Action.

## New Changes

- [x] Removed `setup.sh` script
- [x] Added a new conditional step in `action.yml` for JSON-RPC-Relay installation

## Related Issue
Closes #2 

## Testing
- [x] Tested with `installRelay: false` (default behavior)
- [x] Tested with `installRelay: true` (installs JSON-RPC-Relay)
- [x] Verified that the relay is properly installed and functional when enabled
- [x] Validate the conditional logic for the `installRelay` parameter in the GitHub Action using if statements to ensure correct behavior.

### CODE REVIEW

**Comment by Firdous2307** [comment]
@hendrikebbers When I ran the workflow in the main branch and my feature branch , I got the following below from the `basic.yml` and `mirrorNode.yml`

Screenshot (1241)

Screenshot (1242)

Screenshot (1243)

Screenshot (1244)

**Comment by hendrikebbers** [comment]
@Firdous2307 we can do the if check directly in the GitHub Action. GitHub supports that: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsif
By doing so the code would be way easier.

**Comment by hendrikebbers** [comment]
are you willing to change that?

**Comment by Firdous2307** [comment]
@hendrikebbers, I tested both scenarios for true and false values and implemented GitHub Actions with conditional logic.
More information : https://github.com/Firdous2307/hedera-solo-action/actions

**Review by hendrikebbers — APPROVED** [review]

**Comment by hendrikebbers** [comment]
@Firdous2307 thank you very much

**Comment by Firdous2307** [comment]
> @Firdous2307 thank you very much

NO problem, my first PR!!!

**Pull request merged**
